const actionTypes = {
  SET_PRODUCTS: 'mainPage/SET_PRODUCTS',
  SET_IS_FETCHING: 'mainPge/SET_IS_FETCHING',
  SET_ADD_CART_PRODUCTS: 'mainPge/SET_ADD_CART_PRODUCTS',
  SET_PRODUCTS_DETAILS: 'mainPge/SET_PRODUCTS_DETAILS',
  SET_REMOVE_CART_PRODUCTS: 'mainPge/SET_REMOVE_CART_PRODUCTS',
  SET_CLEAR_CART: 'mainPge/SET_CLEAR_CART',
  SET_REMOVE_ONE_PRODUCT: 'mainPge/SET_REMOVE_ONE_PRODUCT',
  SET_TO_LIST: 'mainPge/SET_TO_LIST',
  SET_TO_GRID: 'mainPge/SET_TO_GRID'
};

export default actionTypes;